### 딥러닝을 가능케한 autograd

In [3]:
import torch

In [4]:
x=torch.tensor([1.], requires_grad=True)
print(x)

tensor([1.], requires_grad=True)


In [6]:
x=torch.tensor([1.])
print(x)
print(x.requires_grad)

x.requires_grad=True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [9]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y)

print(x.grad)
y.backward()
print(x.grad) # y=x**2을 미분한 2x의 x값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y)
# y.retain_grad() # 이걸 하면 y.grad도 볼 수 있음

z=3*y
print(z) # MulBackward0 가 붙어있음

z.backward() # reguires_grad=True인 애들에 대해서만 gradient 계산
print(x.grad) # chained rule에 의해 계산된 값
# print(y.grad) # warning! 중간건 안됨

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
z=3*y

y.backward()
print(x.grad) # 이렇게하면 y에서부터 뒤로 넘어감

tensor([2.])


In [18]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙었음
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
x=torch.tensor([1.], requires_grad=True)
y=torch.tensor([1.], requires_grad=True)
z=2*x**2 + y**2
print(z)
z.backward() # z가 가진 requires_grad=True인 애들에 대해서 gradient 계산
print(x.grad) # x로 편미분 후 x=1 대입
print(y.grad) # y로 편미분 후 y=1 대입

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [23]:
x=torch.tensor([1.], requires_grad=True)
y=torch.tensor([1.], requires_grad=True)
z=y*x**2
print(z)
z.backward() # z가 가진 requires_grad=True인 애들에 대해서 gradient 계산
print(x.grad) # x로 편미분 후 x=1 대입
print(y.grad) # y로 편미분 후 y=1 대입

tensor([1.], grad_fn=<MulBackward0>)
tensor([2.])
tensor([1.])


In [ ]:
x=torch.tensor([1., 2., 3.], requires_grad=True)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [25]:
x=torch.tensor([1.], requires_grad=True)
x.requires_grad=False
# transfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [ ]:
x=torch.tensor([2.], requires_grad=True)
