### numpy와 닮은 파이토치(pytorch)

In [2]:
import torch
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
print(torch.__version__)

NVIDIA GeForce RTX 4070 SUPER
True
2.8.0+cu126


In [3]:
a=torch.tensor([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b) 

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [4]:
A=torch.tensor([[1,2,3],[3,4,5]]) # 이 셀부터는 import torch 는 실행했다 치고 작성
# A=torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [5]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [6]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b # 덧셈은? 성분끼리의 합! (벡터 덧셈)
print(c)

tensor([5, 7, 9])


In [7]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [8]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱
print(A.matmul(B)) # 위와 동일

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


### pytorch의 인덱싱과 슬라이싱

In [9]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:]) # 이상
print(a[:7]) # 미만
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B = [[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # 리스트는 안됨
print(A[1,:]) # 1행, 전체
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [ ]:
# 3차원 행렬 인덱싱
A=torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
               [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(A)
print(A.shape)
print(A[0,1,2])

a=torch.tensor([1,2,3,4]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가된다.
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([4])
